name: ​🐞 Bug
description: Report an issue to help us improve the project.
title: "BUG REPORT<title>"
labels: ["bug", "goal: fix"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A brief description of the issue or bug you are facing, include what you tried and what didn't work
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots or videos if applicable
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information or anything we should know about this bug?
    validations:
      required: false
  - type: dropdown
    attributes:
      label: What browser are you seeing this bug on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing issues"
          required: true

        - label: "I have read the Contributing Guidelines"
          required: true

        - label: "I have read the Code Of Conduct"
          required: true

        - label: "The changes don't break the code"
          required: true
