name: Auto Comment on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
     - name: Add Comment to Merged PR
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         curl -H "Authorization: token $GITHUB_TOKEN" \
         -X POST \
         -d '{"body":"🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution! Your changes are now part of the main branch and will be included in the next release.
                        If you haven't done so already, consider starring our repository! Starring helps to bookmark the repository for easy access and shows your support and appreciation.Your efforts are greatly appreciated. Keep up the fantastic work! 🚀"}' \
         "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
