name: Pull Request related comments
on:
  pull_request_target:
    types:
      - opened
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Opening Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const {owner, repo, number} = context.issue;
            const commentAuthor = context.payload.sender.login;
            const commentBody = `Hey @${ commentAuthor }, Thank you for creating PR! Will review it super soon.
            Don’t forget to ⭐ the repository!
            Will see you soon!`;
            await github.issues.createComment({owner, repo, issue_number : number, body: commentBody});
            console.log('Commented on PR');
